version: "2.3"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8095:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/embyCache:/var/cache/nginx/emby
    restart: always
    depends_on:
      - audiobookshelf
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    environment:
      - AUDIOBOOKSHELF_UID=0
      - AUDIOBOOKSHELF_GID=0
    ports:
      - 13378:80
    volumes:
      - /srv/dev-disk-by-uuid-51433fa1-0994-4003-be4b-f47e3f50c13f/video:/audiobooks
      - ./config:/config
      - ./metadata:/metadata