version: "2.1"
services:
  pan_115:
    build: .
    container_name: pan_115
    environment:
      - USER_ID=0
      - GROUP_ID=0
    volumes:
      - ./Downloads/:/config/Downloads/115download
    ports:
       - 5900:5900
       - 5800:5800
