version: "2.3"
services:
  emby:
    image: xinjiawei1/emby_unlockd:latest
    container_name: embyserver
    environment:
      - UID=0
      - GID=0
      - GIDLIST=0
    volumes:
      - ./config:/config
      - /srv/dev-disk-by-uuid-c78a92c0-7c20-4480-b997-1f88c9d0cd4d:/mnt/share
    ports:
      - "8096:8096"
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped