version: "2.1"
services:
  kodexplorer:
    image: baiyuetribe/kodexplorer
    container_name: kodexplorer
    volumes:
      - /srv/dev-disk-by-uuid-51433fa1-0994-4003-be4b-f47e3f50c13f/Documents:/var/www/html/Documents
    ports:
      - "889:80"
    restart: unless-stopped